<a href="https://colab.research.google.com/github/dhfricard-coder/macro-regime-classifier/blob/main/01_setup_and_fred_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install fredapi pandas numpy scikit-learn hmmlearn plotly matplotlib

Collecting fredapi
  Downloading fredapi-0.5.2-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting hmmlearn
  Downloading hmmlearn-0.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading fredapi-0.5.2-py3-none-any.whl (11 kB)
Downloading hmmlearn-0.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (165 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 kB 8.6 MB/s eta 0:00:00
Installing collected packages: hmmlearn, fredapi
Successfully installed fredapi-0.5.2 hmmlearn-0.3.3

In [2]:
# I create this field ('FRED_API_KEY') to store key for FRED API
import os
os.environ["FRED_API_KEY"] = "txt"

In [3]:
# I access FRED API
from fredapi import Fred
import pandas as pd
import numpy as np
import os

fred = Fred(api_key=os.getenv("FRED_API_KEY"))

In [4]:
# Check if i can import unemployment data
series = fred.get_series("UNRATE")
series.tail()

2025-10-01    NaN
2025-11-01    4.5
2025-12-01    4.4
2026-01-01    4.3
2026-02-01    4.4
dtype: float64

In [5]:
# Importing macro data from Federal Reserve Bank of St Louis (a very reliable source for Macro data)
data = {
    'cpi_yoy': fred.get_series('CPIAUCSL').pct_change(12)*100,
    'ism_mfg': fred.get_series('MANEMP'),
    'yield_curve': fred .get_series('T10Y2Y'),
    'real_rate' : fred.get_series('DFII10'),
    'credit_spread' : fred.get_series('BAMLH0A0HYM2'),
    'unemployment_chg' : fred.get_series('UNRATE').diff(3)
}

df = pd.DataFrame(data).dropna()
df.head()

/tmp/ipykernel_946/1079508432.py:3: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  'cpi_yoy': fred.get_series('CPIAUCSL').pct_change(12)*100,

,cpi_yoy,ism_mfg,yield_curve,real_rate,credit_spread,unemployment_chg
2003-04-01,2.175125,14608.0,2.34,2.02,7.61,0.2
2003-05-01,1.894150,14558.0,2.38,2.13,6.37,0.2
2003-07-01,2.055556,14403.0,2.26,1.92,6.15,0.2
2003-08-01,2.216066,14376.0,2.59,2.40,5.77,0.0
2003-10-01,2.041943,14334.0,2.49,1.96,5.46,-0.2